### ISSUE TITLE
WCUBE contract interaction 

### ISSUE THREAD

**Issue by Endijuan33** [cube-network/docs#1]
for developers, please add a "deposit" option to the WCUBE contract. so that users can interact directly without having to wrap through dapps

I'm trying to interact via walletconnect on the wcube contract address 
my wallet address:
0x53914bda3129b21F9B0708f1e7ee675dF22261fe

**Comment by Nanyan** [comment]
Sorry but there is a `deposit` function in the `WCUBE` contract: <https://testnet.cubescan.network/en-us/address/0xb9164670a2f388d835b868b3d0d441fa1be5bb00?type=contract>

The function is as follow:
```
    function deposit() public payable {
        balanceOf[msg.sender] += msg.value;
        emit Deposit(msg.sender, msg.value);
    }
```

**Comment by Endijuan33** [comment]
> Sorry but there is a `deposit` function in the `WCUBE` contract: https://testnet.cubescan.network/en-us/address/0xb9164670a2f388d835b868b3d0d441fa1be5bb00?type=contract
> 
> The function is as follow:
> 
> ```
>     function deposit() public payable {
>         balanceOf[msg.sender] += msg.value;
>         emit Deposit(msg.sender, msg.value);
>     }
> ```
> 
> More over, it can also receive `CUBE` directly:
> 
> ```
>     receive() external payable {
>         deposit();
>     }
> ```

**Comment by Endijuan33** [comment]
okay, thanks for solving this issue, i will give it a try

**Comment by Endijuan33** [comment]
![Screenshot_2022-05-27-20-59-38-293_com yandex browser](https://user-images.githubusercontent.com/28471097/170714504-84a9f3e1-9a5c-4346-9f7b-ca0c8c421345.jpg)
sorry but I'm still confused because there is no "deposit" option. am i wrong about that?

**Comment by Nanyan** [comment]
Thanks for your report, I will forward this to the dev team of the CubeScan.
Before it’s fixed, maybe you can just send CUBE to the contact address 0xb9164670a2f388d835b868b3d0d441fa1be5bb00 instead of using the deposit function.

**Comment by Nanyan** [comment]
The issue is fixed. Now we can interact with a function without input arguments in the CubeScan.
